### PR TITLE
Moar Optz

### PR DESCRIPTION
**Pull request by CheckYourScreen**
Merge After testing on op2 and Mi5.
@B--B  @MZO9400

### CODE REVIEW

**Comment by MZO9400** [comment]
👍

**Comment by CheckYourScreen** [comment]
Working fine for onyx, ready to merge.
Check oneplus 2 once, wont merge this one until you run a build xD

**Comment by B--B** [comment]
Hi there! Big thanks for this, this evening hopefully i will have time for review and test it! :) Sorry but i'm so busy in these days, and actually my priority is release the jf version, already build but not tested well yet...! :(

**Comment by MZO9400** [comment]
No-go for OP2. Lots of Libm errors

**Comment by B--B** [comment]
https://github.com/AOSP-JF-MM/platform_bionic/commit/bb798f444c5a4c102bef82202f264acc4e15e2aa Fixed compiling for Kryo target, hopefully Krait is fixed too

**Comment by MZO9400** [comment]
I believe the relation is with https://github.com/CheckYourScreen/platform_bionic/commit/156112a9f3b694c41860ead2bef98fcc1764431f, let me revert and check

**Comment by CheckYourScreen** [comment]
Thats strange, onyx compiled and booted fine with all commits.
The new lib might cause some issue for 64bit so didn't merge this PR without you all testing it.

**Comment by MZO9400** [comment]
This too https://github.com/CheckYourScreen/platform_bionic/commit/4fc3e9dbc55fa945f96195ac86a258f94be0460d, reverted these two and so far so good. Still building though

**Comment by B--B** [comment]
Still broken for me too, strcmp compiles fine but seems that we still miss something :)

**Comment by CheckYourScreen** [comment]
https://github.com/AOSP-JF-MM/platform_bionic/pull/1/commits/9c2bb5ee9143557d57c5699271e0c7fb20f1d2d8

This might be the culprit

**Comment by CheckYourScreen** [comment]
Found what we were missing...... *sigh*

https://github.com/AOSPA/android_bionic/commits/nougat-mr2?author=xboxfanj

**Comment by B--B** [comment]
We need more changes in other repos for support aarch32 changes properly, I've already merged the changes locally, if build and boots fine i will push everything :)

**Comment by smeroni68** [comment]
Nice to see this good collaboration!! ;)

**Comment by MZO9400** [comment]
@smeroni68 oh yeah! 

@checkyourscreen @b--b my build went through just fine after I reverted those​ libm commits

**Comment by B--B** [comment]
So near... Please take a look here:
https://github.com/AOSP-JF-MM/platform_frameworks_native/tree/PR
https://github.com/AOSP-JF-MM/platform_external_libunwind_llvm
https://github.com/AOSP-JF-MM/platform_external_vulkan-validation-layers
https://github.com/AOSP-JF-MM/platform_bionic/tree/PR

Had to revert this for now: 9cd3e34e824d15f6fba6f7f21f0e7e1ead928bbd otherwise my build breaks, haven't faced yet what's wrong with it, but may be related to kryo routines i merged from upstream and this: https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/78889946b6f1c521cf5ab5d6f50163fc0deaf415 , i must take a look better :)
Could you guys try this set of changes and see if build and boots with and without that revert? :) Jf not tested, Mi5 boots fine, everything else not tested yet :)

EDIT: also fixed root flashing https://github.com/AOSP-JF-MM/platform_build/commit/8b947972ea258ae3c655b6552503ca822fa08b08 , should be fine for both root/unrooted ROMs

EDIT 2: reverted some CAF stuffs that we don't need

**Comment by CheckYourScreen** [comment]
Seems good to me.
Merge all the changes and branches in aosp-7.1.2, lets roll 😉

**Comment by B--B** [comment]
Ok, now everything should be fine :) Ported all the missing kryo stuffs, compiles fine, boots and works on Mi5
Also ported all needed changes on skia and libjpeg-turbo
Art and dex2oat now should be fine too, no errors for me in logcat using kryo variant :)
Use my test branch on bionic for compiling for the moment, i want to try another thing before rebase and merge everything in aosp-7.1.2 branch :)

**Comment by CheckYourScreen** [comment]
@B--B Meanwhile can you do the Ticker and Soft/hw nav keys toggle too?

**Pull request merged**
